### ISSUE TITLE
Basic auth has been removed in 4.5.1 so Plugin needs update to Keycloak

### ISSUE THREAD

**Issue by Schamane187** [tesibelda/ovirtstat#1]
Hi,

Ovirt has removed Basic Auth in 4.5.1 

I also stumbled over that in virt-v2v, where it is fixed now.
https://github.com/libguestfs/virt-v2v/issues/42

If I try to use your plugin it gives me 

"failed to gather metrics: could not to get API summary from https://hostname/ovirt-engine/api: Error during SSO authentication access_denied : Cannot authenticate user No valid profile found in credentials.."

I also had to switch my RestAPI scripts to OAuth authentication, but in this plugin I don't know how.

Maybe I am just doing something wrong, but I am pretty sure it's because of missing basic Auth.

thanks in advance

**Comment by tesibelda** [comment]
Hi Schamane187,
  I don't currently have access to an oVirt v4.5.1 or higher to test this, but the docs at https://www.ovirt.org/release/4.5.1/ explain that there is a change regarding users for REST API. For example for admin user it changes from ‘admin@internal’ to ‘admin@ovirt@internalsso’. Can you try configuring the user name using that schema in the username configuration parameter? like:

```toml
ovirturl = "https://ovirt-engine.local/ovirt-engine/api"
username = "user@ovirt@internalsso"
password = "secret"
```
or
```toml
ovirturl = "https://ovirt-engine.local/"
username = "user@ovirt@internalsso"
password = "secret"
```
